[package]
name = "spf"
version = "0.1.0"
authors = ["Snow Pettersen <aickck@gmail.com>"]

[dependencies]
bcc = { path = "../rust-bcc" }
failure = "0.1.5"
ctrlc = "3.1.3"
clap = "2.33.0"
colored = "1.8"
byteorder = "1.3.2"
hpack = "0.3.0"
