[package]
name = "spf"
version = "0.1.0"
authors = ["Snow Pettersen <aickck@gmail.com>"]

[dependencies]
bcc = { path = "../rust-bcc" }
failure = "0.1.5"
ctrlc = "3.1.3"
base64 = "0.10.0"
colored = "1.8"
